---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-db
data:
  database: wordpress
  user: wp
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db
data:
  password: aHVudGVyMg==
  rootPassword: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Service
metadata:
  name: wp-db
  labels:
    app: wordpress-db
spec:
  type: ClusterIP
  selector:
    app: wordpress-db
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress-db
  labels:
    app: wordpress-db
spec:
  selector:
    matchLabels:
      app: wordpress-db
  serviceName: wp-db
  replicas: 1
  template:
    # Pod
    metadata:
      labels:
        app: wordpress-db
    spec:
      containers:
        - name: mariadb
          image: mariadb
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: wordpress-db
                  key: database
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: wordpress-db
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-db
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-db
                  key: rootPassword
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 2Gi
