apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress
spec:
  rules:
  - host: wordpress
    http:
      paths:
      - backend:
          service:
            name: wordpress
            port:
              name: http
        path: /
        pathType: Prefix
